server:
  port: 80
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://120.79.74.174:3306/liangzhifa?serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: xiaojian
    password: xiaojian
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*
pagehelper:
  auto-dialect: mysql