server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://120.79.74.174:3306/liangzhifa?serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: xiaojian
    password: xiaojian
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*