server:
  port: 80
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://47.100.45.101:3306/liangzhifa?serverTimezone=Asia/Shanghai&useAffectedRows=true&useSSL=true
    username: root
    password: zhifa123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*
pagehelper:
  auto-dialect: mysql